# Generated by Django 4.2.17 on 2024-12-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
